// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/weather": {
            "get": {
                "description": "Returns current weather for coordinates or a supported city",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weather"
                ],
                "summary": "Get current weather",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Latitude",
                        "name": "lat",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Longitude",
                        "name": "lon",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "City name (Minsk, London, Tokyo, Shanghai, Warsaw)",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "openweather",
                            "google"
                        ],
                        "type": "string",
                        "default": "openweather",
                        "description": "Weather provider",
                        "name": "provider",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse-weather_CurrentWeather"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.StatusResponse"
                        }
                    }
                }
            }
        },
        "/weather/batch": {
            "get": {
                "description": "Returns current temperature for several supported cities",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weather"
                ],
                "summary": "Get current weather for multiple cities",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated city names",
                        "name": "cities",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "openweather",
                            "google"
                        ],
                        "type": "string",
                        "default": "openweather",
                        "description": "Weather provider",
                        "name": "provider",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse-weather_BatchCurrentWeather"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.StatusResponse"
                        }
                    }
                }
            }
        },
        "/weather/forecast": {
            "get": {
                "description": "Returns weather forecast for coordinates or a supported city",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weather"
                ],
                "summary": "Get weather forecast",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Latitude",
                        "name": "lat",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Longitude",
                        "name": "lon",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "City name (Minsk, London, Tokyo, Shanghai, Warsaw)",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 24,
                        "description": "Forecast horizon in hours",
                        "name": "hours",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "openweather",
                            "google"
                        ],
                        "type": "string",
                        "default": "openweather",
                        "description": "Weather provider",
                        "name": "provider",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse-weather_WeatherForecast"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.StatusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "responses.StatusResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.SuccessResponse-weather_BatchCurrentWeather": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/weather.BatchCurrentWeather"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.SuccessResponse-weather_CurrentWeather": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/weather.CurrentWeather"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.SuccessResponse-weather_WeatherForecast": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/weather.WeatherForecast"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "weather.BatchCurrentWeather": {
            "type": "object",
            "properties": {
                "locations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/weather.LocationWeather"
                    }
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "weather.CurrentWeather": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "weather.ForecastItem": {
            "type": "object",
            "properties": {
                "temperature": {
                    "type": "number"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "weather.LocationWeather": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "weather.WeatherForecast": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/weather.ForecastItem"
                    }
                },
                "location": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Weather Example API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
